#!/bin/bash
#[php]
sudo /etc/init.d/php7.0-fpm stop
# (start|stop|restart)
#[mysql]
sudo service mysql stop
#[nginx]
sudo kill -9 $(pidof nginx)
#[mongodb]
sudo kill -9 $(pidof mongodb)
echo '=============done==========='